<?php

declare(strict_types=1);

namespace LogoObjects;

/**
 * Tum endpoint adlari -> URL yolu. Tanitim/listeleme amacli.
 */
final class Endpoints
{
    /** @var array<string,string> */
    private static $map = [
        'additionalTaxes' => '/additionalTaxes',
        'ArpGroupAssignments' => '/ArpGroupAssignments',
        'ArpMLDescriptons' => '/ArpMLDescriptons',
        'Arps' => '/Arps',
        'ArpShipmentLocations' => '/ArpShipmentLocations',
        'ArpSlips' => '/ArpSlips',
        'authorizationCodes' => '/authorizationCodes',
        'bankAccounts' => '/bankAccounts',
        'bankCredits' => '/bankCredits',
        'bankMLDescriptions' => '/bankMLDescriptions',
        'banks' => '/banks',
        'bankSlips' => '/bankSlips',
        'Boms' => '/Boms',
        'BomStandardCosts' => '/BomStandardCosts',
        'CAPI' => '/CAPI',
        'characteristics' => '/characteristics',
        'characteristicSets' => '/characteristicSets',
        'chequeAndPnoteRolls' => '/chequeAndPnoteRolls',
        'chequeAndPnotes' => '/chequeAndPnotes',
        'cities' => '/cities',
        'collateralRolls' => '/collateralRolls',
        'contacts' => '/contacts',
        'costDistributionSlips' => '/costDistributionSlips',
        'countries' => '/countries',
        'customerMLDescriptions' => '/customerMLDescriptions',
        'customers' => '/customers',
        'customersOfSalesmen' => '/customersOfSalesmen',
        'customsOffices' => '/customsOffices',
        'dbinfo' => '/dbinfo',
        'definitions' => '/definitions',
        'deliveryCodes' => '/deliveryCodes',
        'demandPeggings' => '/demandPeggings',
        'demandSlips' => '/demandSlips',
        'distributionOrders' => '/distributionOrders',
        'distributionRoutes' => '/distributionRoutes',
        'distributionTemplates' => '/distributionTemplates',
        'districts' => '/districts',
        'employeeCosts' => '/employeeCosts',
        'employeeGroups' => '/employeeGroups',
        'employees' => '/employees',
        'employeeStandardCosts' => '/employeeStandardCosts',
        'engineeringChanges' => '/engineeringChanges',
        'exportCreditLetters' => '/exportCreditLetters',
        'exportCredits' => '/exportCredits',
        'exportMovementSlips' => '/exportMovementSlips',
        'exportNationalizationSlips' => '/exportNationalizationSlips',
        'exportOperationSlips' => '/exportOperationSlips',
        'exportTypedPurchaseInvoices' => '/exportTypedPurchaseInvoices',
        'exportTypedSalesInvoices' => '/exportTypedSalesInvoices',
        'extendedFieldCategories' => '/extendedFieldCategories',
        'extendedFieldDefinitions' => '/extendedFieldDefinitions',
        'extendedFields' => '/extendedFields',
        'FAAssignmentSlips' => '/FAAssignmentSlips',
        'FARegistries' => '/FARegistries',
        'Firmdocs' => '/Firmdocs',
        'freeZones' => '/freeZones',
        'GLAccountMLDescriptions' => '/GLAccountMLDescriptions',
        'GLAccounts' => '/GLAccounts',
        'GLSlips' => '/GLSlips',
        'groupCodes' => '/groupCodes',
        'importCreditLetters' => '/importCreditLetters',
        'importDistributionSlips' => '/importDistributionSlips',
        'importOperationSlips' => '/importOperationSlips',
        'inwardProcessingPermits' => '/inwardProcessingPermits',
        'istokenvalid' => '/istokenvalid',
        'itemAlternatives' => '/itemAlternatives',
        'itemBoms' => '/itemBoms',
        'itemBrands' => '/itemBrands',
        'itemCharacteristics' => '/itemCharacteristics',
        'itemClassAssignments' => '/itemClassAssignments',
        'itemMLDescriptions' => '/itemMLDescriptions',
        'items' => '/items',
        'itemSlips' => '/itemSlips',
        'itemStandardCosts' => '/itemStandardCosts',
        'licenses' => '/licenses',
        'locationCodes' => '/locationCodes',
        'methods' => '/methods',
        'operations' => '/operations',
        'opportunities' => '/opportunities',
        'overheadAccounts' => '/overheadAccounts',
        'paymentDifferenceInvoices' => '/paymentDifferenceInvoices',
        'paymentPlanGroupCodes' => '/paymentPlanGroupCodes',
        'paymentPlans' => '/paymentPlans',
        'ping' => '/ping',
        'postCodes' => '/postCodes',
        'productionExceptions' => '/productionExceptions',
        'productionLines' => '/productionLines',
        'productionParameters' => '/productionParameters',
        'productionResourceUtilization' => '/productionResourceUtilization',
        'productionRoutes' => '/productionRoutes',
        'productions' => '/productions',
        'projects' => '/projects',
        'purchaseCampaigns' => '/purchaseCampaigns',
        'purchaseConditionsForSlipLines' => '/purchaseConditionsForSlipLines',
        'purchaseConditionsForSlips' => '/purchaseConditionsForSlips',
        'purchaseDiscounts' => '/purchaseDiscounts',
        'purchaseDispatches' => '/purchaseDispatches',
        'purchasedItemPrices' => '/purchasedItemPrices',
        'purchasedServicePrices' => '/purchasedServicePrices',
        'purchasedServices' => '/purchasedServices',
        'purchaseExpenses' => '/purchaseExpenses',
        'purchaseInvoices' => '/purchaseInvoices',
        'purchaseOrders' => '/purchaseOrders',
        'purchasePromotions' => '/purchasePromotions',
        'purchaseProposalContracts' => '/purchaseProposalContracts',
        'purchaseProposalOffers' => '/purchaseProposalOffers',
        'purchaseProposalOrders' => '/purchaseProposalOrders',
        'QCCriteriaAssignments' => '/QCCriteriaAssignments',
        'QCCriteriaSets' => '/QCCriteriaSets',
        'Queries' => '/Queries',
        'quickProductionSlips' => '/quickProductionSlips',
        'repaymentPlans' => '/repaymentPlans',
        'revoke' => '/revoke',
        'safeDeposits' => '/safeDeposits',
        'safeDepositSlips' => '/safeDepositSlips',
        'salesActivities' => '/salesActivities',
        'salesCampaigns' => '/salesCampaigns',
        'salesCategories' => '/salesCategories',
        'salesConditionsForSlipLines' => '/salesConditionsForSlipLines',
        'salesConditionsForSlips' => '/salesConditionsForSlips',
        'salesContracts' => '/salesContracts',
        'salesDiscounts' => '/salesDiscounts',
        'salesDispatches' => '/salesDispatches',
        'salesExpenses' => '/salesExpenses',
        'salesInvoices' => '/salesInvoices',
        'salesItemPrices' => '/salesItemPrices',
        'salesmanDestinations' => '/salesmanDestinations',
        'salesmanPositionCodes' => '/salesmanPositionCodes',
        'salesmanRoutes' => '/salesmanRoutes',
        'salesmen' => '/salesmen',
        'salesOffers' => '/salesOffers',
        'salesOrders' => '/salesOrders',
        'salesPromotions' => '/salesPromotions',
        'salesProvisionDistributionSlips' => '/salesProvisionDistributionSlips',
        'salesServicePrices' => '/salesServicePrices',
        'serialAndLotNumbers' => '/serialAndLotNumbers',
        'services' => '/services',
        'shiftAssignments' => '/shiftAssignments',
        'shifts' => '/shifts',
        'soldServices' => '/soldServices',
        'specialCodes' => '/specialCodes',
        'standardCostPeriods' => '/standardCostPeriods',
        'stopCauses' => '/stopCauses',
        'sys' => '/sys',
        'towns' => '/towns',
        'trackables' => '/trackables',
        'transaction' => '/transaction',
        'unitSets' => '/unitSets',
        'variants' => '/variants',
        'vehicles' => '/vehicles',
        'workflowDefinitions' => '/workflowDefinitions',
        'workflowRoles' => '/workflowRoles',
        'workstationCosts' => '/workstationCosts',
        'workstationGroups' => '/workstationGroups',
        'workstations' => '/workstations',
        'workstationStandardCosts' => '/workstationStandardCosts',
    ];

    /** @return array<string,string> */
    public static function all(): array
    {
        return self::$map;
    }

    public static function has(string $name): bool
    {
        return isset(self::$map[$name]);
    }

    public static function path(string $name): ?string
    {
        return self::$map[$name] ?? null;
    }

    public static function count(): int
    {
        return count(self::$map);
    }
}
